"""Renamed soft_skill_match to soft_skills_match

Revision ID: 3fb9a4b3ce72
Revises: ce83a6329c22
Create Date: 2025-03-15 12:43:33.861790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb9a4b3ce72'
down_revision: Union[str, None] = 'ce83a6329c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('soft_skills_match', sa.Float(), nullable=True))
    op.drop_column('job_matches', 'soft_skill_match')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('soft_skill_match', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('job_matches', 'soft_skills_match')
    # ### end Alembic commands ###
