"""Renamed technical_match to tech_match

Revision ID: ce83a6329c22
Revises: caadf5a67e0c
Create Date: 2025-03-15 12:39:37.421969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce83a6329c22'
down_revision: Union[str, None] = 'caadf5a67e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('tech_match', sa.Float(), nullable=True))
    op.drop_column('job_matches', 'technical_match')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('technical_match', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('job_matches', 'tech_match')
    # ### end Alembic commands ###
